/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
package codeeditor;

import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.JTextPane;
import javax.swing.text.Highlighter;

/**
 *
 * @author norps
 */
public class DialogFindReplace extends javax.swing.JDialog {
    //JTextPane textPane;
    /**
     * Creates new form FindReplace
     */
    PanelFindReplace njp1;
    PanelFindReplace njp2;
    public DialogFindReplace(java.awt.Frame parent, boolean modal,JTextPane textPane,Highlighter hilit,int selectedIndex) {
        super(parent, modal);
        njp1=new PanelFindReplace(textPane, hilit, this);
        njp2=new PanelFindReplace(textPane, hilit, this);
        initComponents();
        tabMain.add("Find",njp1);
        tabMain.add("Replace",njp2);
        setVisible(true);
        tabMain.setSelectedIndex(selectedIndex);
    }
    
    public void close(){
       this.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        tabMain.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabMainStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabMainStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabMainStateChanged
           if(tabMain.getSelectedIndex()==0){
               njp1.panelFind();
           }
           else
               njp2.panelReplace();
    }//GEN-LAST:event_tabMainStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabMain;
    // End of variables declaration//GEN-END:variables



   
    
}

